#!/bin/bash
# $Id: chksendmail,v 1.2 2019/07/02 09:21:17 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/chksendmail,v $
# $Revision: 1.2 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: chksendmail,v 1.2 2019/07/02 09:21:17 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;			
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.2 $ $Date: 2019/07/02 09:21:17 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done


count=`ssh mailhost ps -ef|grep sendmail|wc -l`
if [ $count -gt 9 ] ;then
	wall "Alert. Excessive number of sendmail instances"
fi
